services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/kevin/bot
      - ./db:/db/bot
      - ./log/bot:/log
    command: npm run dev
  rules:
    build:
      context: .
      dockerfile: ./rules.Dockerfile
    volumes:
      - ./log/rules:/log
    command: 
      - /wait-for-it.sh
      - bot:8080
      - --
      - /run_rules.sh