services:
  bot:
    build:
      context: ./bot
      target: development
    volumes:
      - ./bot:/kevin/bot
      - ./db:/db
      - ./log/bot:/log
  rules:
    build:
      context: .
      dockerfile: ./rules.Dockerfile
    volumes:
      - ./log/rules:/log
    command: 
      - /wait-for-it.sh
      - bot:8080
      - --
      - /run_rules.sh