services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/kevin/bot
    command: npm run dev
  rules:
    build:
      context: .
      dockerfile: ./rules.Dockerfile
    volumes:
      - ./logs:/logs
    command: 
      - /wait-for-it.sh
      - bot:8080
      - --
      - /run_rules.sh