name: Test Cases

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run: docker build bot/ --target=test --tag test
            - name:
              run: docker run test
